#!/usr/bin/env python3
"""Genera las filas CSV para los 42 municipios de la RM que faltan."""

import csv, os

HEADERS = ["municipio_id","municipio_nombre","region","pop","web","cat","cat_emoji","titulo","desc","como","url"]

RM = "Región Metropolitana"

nuevos = [
# ─── PROVINCIA DE SANTIAGO ────────────────────────────────────────────
# Cerrillos
["cerrillos","Cerrillos",RM,"95.000 hab.","https://municipalidadcerrillos.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Red de centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa inscritos.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://municipalidadcerrillos.cl/salud/"],
["cerrillos","Cerrillos",RM,"95.000 hab.","https://municipalidadcerrillos.cl","Salud","🏥","Farmacia Municipal Cerrillos","Medicamentos esenciales a precio accesible para vecinos de Cerrillos con receta médica vigente.","Presenta receta médica en la farmacia municipal. Sin trámites adicionales.","https://municipalidadcerrillos.cl/"],
["cerrillos","Cerrillos",RM,"95.000 hab.","https://municipalidadcerrillos.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Cerrillos con vulnerabilidad y buen rendimiento en educación superior.","Postula entre marzo y abril en la Municipalidad con RSH, certificado de matrícula y notas.","https://municipalidadcerrillos.cl/educacion/"],
["cerrillos","Cerrillos",RM,"95.000 hab.","https://municipalidadcerrillos.cl","Adulto Mayor","👴","Programa Adulto Mayor Cerrillos","Talleres recreativos, actividad física y sociabilización gratuitos para personas mayores de 60 años.","Inscríbete en la Oficina del Adulto Mayor o en los centros comunitarios de tu sector.","https://municipalidadcerrillos.cl/adulto-mayor/"],
["cerrillos","Cerrillos",RM,"95.000 hab.","https://municipalidadcerrillos.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Atención de urgencias sociales, subsidios y orientación para familias vulnerables de Cerrillos.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://municipalidadcerrillos.cl/social/"],

# Conchalí
["conchali","Conchalí",RM,"135.000 hab.","https://mconchali.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad y Fonasa activo.","https://www.mconchali.cl/salud/"],
["conchali","Conchalí",RM,"135.000 hab.","https://mconchali.cl","Salud","🏥","Farmacia Municipal Conchalí","Medicamentos a precio social para vecinos de Conchalí con receta médica. Prioridad familias vulnerables.","Presenta receta médica vigente en la farmacia municipal con carnet de identidad.","https://www.mconchali.cl/"],
["conchali","Conchalí",RM,"135.000 hab.","https://mconchali.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Conchalí con vulnerabilidad económica cursando educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad.","https://www.mconchali.cl/educacion/"],
["conchali","Conchalí",RM,"135.000 hab.","https://mconchali.cl","Adulto Mayor","👴","Talleres y programas adulto mayor","Actividades recreativas, culturales y físicas gratuitas para adultos mayores de Conchalí.","Inscríbete en la Oficina del Adulto Mayor o en tu centro comunitario más cercano.","https://www.mconchali.cl/adulto-mayor/"],
["conchali","Conchalí",RM,"135.000 hab.","https://mconchali.cl","Social y Legal","⚖️","Desarrollo Social Municipal","Urgencias sociales, subsidios estatales y orientación para familias vulnerables de Conchalí.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de lunes a viernes.","https://www.mconchali.cl/social/"],

# El Bosque
["elbosque","El Bosque",RM,"180.000 hab.","https://municelbosque.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Red de centros de salud con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa inscritos.","Inscríbete en el CESFAM de tu sector con carnet. Atención sin costo con Fonasa.","https://www.municelbosque.cl/salud/"],
["elbosque","El Bosque",RM,"180.000 hab.","https://municelbosque.cl","Salud","🏥","Farmacia Municipal El Bosque","Medicamentos esenciales a precio solidario para vecinos de El Bosque con receta médica vigente.","Presenta receta en la farmacia municipal. Requiere carnet y acreditar residencia en la comuna.","https://www.municelbosque.cl/"],
["elbosque","El Bosque",RM,"180.000 hab.","https://municelbosque.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de El Bosque con vulnerabilidad y rendimiento académico.","Postula entre marzo y abril en la Municipalidad con RSH, matrícula y notas.","https://www.municelbosque.cl/educacion/"],
["elbosque","El Bosque",RM,"180.000 hab.","https://municelbosque.cl","Adulto Mayor","👴","Programa Adulto Mayor El Bosque","Talleres gratuitos de actividad física, recreación y sociabilización para mayores de 60 años.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de El Bosque.","https://www.municelbosque.cl/adulto-mayor/"],
["elbosque","El Bosque",RM,"180.000 hab.","https://municelbosque.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Atención de urgencias sociales, subsidios y orientación para familias de El Bosque.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://www.municelbosque.cl/social/"],

# Estación Central
["estacioncentral","Estación Central",RM,"145.000 hab.","https://estacioncentral.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://estacioncentral.cl/salud/"],
["estacioncentral","Estación Central",RM,"145.000 hab.","https://estacioncentral.cl","Salud","🏥","Farmacia Municipal Estación Central","Medicamentos a precio accesible para vecinos de Estación Central con receta médica.","Presenta receta médica vigente en la farmacia municipal con carnet de identidad.","https://estacioncentral.cl/"],
["estacioncentral","Estación Central",RM,"145.000 hab.","https://estacioncentral.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de la comuna con vulnerabilidad cursando educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad.","https://estacioncentral.cl/educacion/"],
["estacioncentral","Estación Central",RM,"145.000 hab.","https://estacioncentral.cl","Adulto Mayor","👴","Programa Adulto Mayor","Talleres de actividad física y recreación gratuitos para personas mayores de 60 años de la comuna.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Estación Central.","https://estacioncentral.cl/adulto-mayor/"],
["estacioncentral","Estación Central",RM,"145.000 hab.","https://estacioncentral.cl","Social y Legal","⚖️","Desarrollo Social Municipal","Urgencias sociales, subsidios y orientación para familias vulnerables de Estación Central.","Acércate con carnet e RSH al Departamento de Desarrollo Social de la Municipalidad.","https://estacioncentral.cl/social/"],

# Huechuraba
["huechuraba","Huechuraba",RM,"115.000 hab.","https://mhuechuraba.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Centros de salud familiar con médico, dental, matrona y salud mental. Atención gratuita con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad y Fonasa activo.","https://www.mhuechuraba.cl/salud/"],
["huechuraba","Huechuraba",RM,"115.000 hab.","https://mhuechuraba.cl","Salud","🏥","Farmacia Municipal Huechuraba","Medicamentos esenciales a precio solidario para vecinos de Huechuraba con receta médica vigente.","Presenta receta médica en la farmacia municipal. Requiere carnet de identidad.","https://www.mhuechuraba.cl/"],
["huechuraba","Huechuraba",RM,"115.000 hab.","https://mhuechuraba.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Huechuraba con vulnerabilidad económica en educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad de Huechuraba.","https://www.mhuechuraba.cl/educacion/"],
["huechuraba","Huechuraba",RM,"115.000 hab.","https://mhuechuraba.cl","Adulto Mayor","👴","Programa Adulto Mayor Huechuraba","Talleres recreativos y de actividad física gratuitos para personas mayores de 60 años.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad.","https://www.mhuechuraba.cl/adulto-mayor/"],
["huechuraba","Huechuraba",RM,"115.000 hab.","https://mhuechuraba.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Atención de urgencias sociales, subsidios y orientación para familias de Huechuraba.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://www.mhuechuraba.cl/social/"],

# Independencia
["independencia","Independencia",RM,"110.000 hab.","https://mindependencia.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://www.mindependencia.cl/salud/"],
["independencia","Independencia",RM,"110.000 hab.","https://mindependencia.cl","Salud","🏥","Farmacia Municipal Independencia","Medicamentos a precio accesible para vecinos con receta médica vigente.","Presenta receta médica en la farmacia municipal con carnet de identidad.","https://www.mindependencia.cl/"],
["independencia","Independencia",RM,"110.000 hab.","https://mindependencia.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Independencia con vulnerabilidad cursando educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad.","https://www.mindependencia.cl/educacion/"],
["independencia","Independencia",RM,"110.000 hab.","https://mindependencia.cl","Adulto Mayor","👴","Programa Adulto Mayor Independencia","Talleres gratuitos de recreación y actividad física para personas mayores de 60 años.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Independencia.","https://www.mindependencia.cl/adulto-mayor/"],
["independencia","Independencia",RM,"110.000 hab.","https://mindependencia.cl","Social y Legal","⚖️","Desarrollo Social Municipal","Urgencias sociales, subsidios y orientación para familias vulnerables de Independencia.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://www.mindependencia.cl/social/"],

# La Cisterna
["lacisterna","La Cisterna",RM,"90.000 hab.","https://municipalidadlacisterna.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Red de centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de tu sector. Atención gratuita con Fonasa activo.","https://municipalidadlacisterna.cl/salud/"],
["lacisterna","La Cisterna",RM,"90.000 hab.","https://municipalidadlacisterna.cl","Salud","🏥","Farmacia Municipal La Cisterna","Medicamentos esenciales a precio solidario para vecinos de La Cisterna con receta médica.","Presenta receta médica vigente en la farmacia municipal con carnet de identidad.","https://municipalidadlacisterna.cl/"],
["lacisterna","La Cisterna",RM,"90.000 hab.","https://municipalidadlacisterna.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de La Cisterna con vulnerabilidad cursando educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad.","https://municipalidadlacisterna.cl/educacion/"],
["lacisterna","La Cisterna",RM,"90.000 hab.","https://municipalidadlacisterna.cl","Adulto Mayor","👴","Programa Adulto Mayor La Cisterna","Talleres recreativos y de actividad física gratuitos para personas mayores de 60 años.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de La Cisterna.","https://municipalidadlacisterna.cl/adulto-mayor/"],
["lacisterna","La Cisterna",RM,"90.000 hab.","https://municipalidadlacisterna.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Atención de urgencias sociales, subsidios y orientación para familias de La Cisterna.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://municipalidadlacisterna.cl/social/"],

# La Granja
["lagranja","La Granja",RM,"130.000 hab.","https://mlagranja.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa inscritos.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://www.mlagranja.cl/salud/"],
["lagranja","La Granja",RM,"130.000 hab.","https://mlagranja.cl","Salud","🏥","Farmacia Municipal La Granja","Medicamentos a precio accesible para vecinos de La Granja con receta médica vigente.","Presenta receta médica en la farmacia municipal con carnet de identidad.","https://www.mlagranja.cl/"],
["lagranja","La Granja",RM,"130.000 hab.","https://mlagranja.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de La Granja con vulnerabilidad económica.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad de La Granja.","https://www.mlagranja.cl/educacion/"],
["lagranja","La Granja",RM,"130.000 hab.","https://mlagranja.cl","Adulto Mayor","👴","Programa Adulto Mayor La Granja","Talleres de actividad física, recreación y sociabilización gratuitos para mayores de 60 años.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad o en tu centro comunitario.","https://www.mlagranja.cl/adulto-mayor/"],
["lagranja","La Granja",RM,"130.000 hab.","https://mlagranja.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Urgencias sociales, subsidios y orientación para familias vulnerables de La Granja.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://www.mlagranja.cl/social/"],

# La Pintana
["lapintana","La Pintana",RM,"195.000 hab.","https://munilapintana.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Red de centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://munilapintana.cl/salud/"],
["lapintana","La Pintana",RM,"195.000 hab.","https://munilapintana.cl","Salud","🏥","Farmacia Municipal La Pintana","Medicamentos esenciales a precio solidario para vecinos con receta médica vigente.","Presenta receta médica vigente en la farmacia municipal con carnet de identidad.","https://munilapintana.cl/"],
["lapintana","La Pintana",RM,"195.000 hab.","https://munilapintana.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de La Pintana con vulnerabilidad cursando educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad.","https://munilapintana.cl/educacion/"],
["lapintana","La Pintana",RM,"195.000 hab.","https://munilapintana.cl","Adulto Mayor","👴","Programa Adulto Mayor La Pintana","Talleres gratuitos de actividad física y recreación para personas mayores de 60 años de La Pintana.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad.","https://munilapintana.cl/adulto-mayor/"],
["lapintana","La Pintana",RM,"195.000 hab.","https://munilapintana.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Atención de urgencias sociales, subsidios y orientación para familias de La Pintana.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://munilapintana.cl/social/"],

# La Reina
["lareina","La Reina",RM,"100.000 hab.","https://lareina.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://lareina.cl/salud/"],
["lareina","La Reina",RM,"100.000 hab.","https://lareina.cl","Salud","🏥","Farmacia Municipal La Reina","Medicamentos a precio accesible para vecinos de La Reina con receta médica vigente.","Presenta receta médica en la farmacia municipal. Requiere carnet y acreditar residencia en la comuna.","https://lareina.cl/"],
["lareina","La Reina",RM,"100.000 hab.","https://lareina.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de La Reina con vulnerabilidad cursando educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad.","https://lareina.cl/educacion/"],
["lareina","La Reina",RM,"100.000 hab.","https://lareina.cl","Adulto Mayor","👴","Centro de Atención Adulto Mayor La Reina","Talleres recreativos, culturales y de actividad física gratuitos para personas mayores de 60 años.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de La Reina.","https://lareina.cl/adulto-mayor/"],
["lareina","La Reina",RM,"100.000 hab.","https://lareina.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Urgencias sociales, subsidios y orientación para familias vulnerables de La Reina.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://lareina.cl/social/"],

# Las Condes
["lascondes","Las Condes",RM,"310.000 hab.","https://lascondes.cl","Salud","🏥","Botiquín de Las Condes — Farmacia Municipal","Medicamentos a precio accesible gestionados por la Corporación de Salud de Las Condes.","Consulta disponibilidad en lascondes.cl. Requiere carnet y acreditar residencia en la comuna.","https://www.lascondes.cl/salud/"],
["lascondes","Las Condes",RM,"310.000 hab.","https://lascondes.cl","Salud","🏥","Óptica Comunal Las Condes","Atención visual y lentes ópticos a precio social para vecinos de Las Condes.","Agenda hora en la Municipalidad o en lascondes.cl. Requiere acreditar residencia en la comuna.","https://www.lascondes.cl/salud/"],
["lascondes","Las Condes",RM,"310.000 hab.","https://lascondes.cl","Salud","🏥","Subsidio de Salud 2026","Apoyo económico anual para vecinos de Las Condes para cubrir gastos de salud.","Postula en la Municipalidad. Requiere RSH y acreditar residencia en Las Condes.","https://www.lascondes.cl/salud/"],
["lascondes","Las Condes",RM,"310.000 hab.","https://lascondes.cl","Educación y Becas","🎓","Becas Enseñanza Superior Las Condes","Apoyo económico para estudiantes de Las Condes en educación superior. Postulación hasta mayo.","Postula en lascondes.cl entre marzo y mayo con matrícula, RSH y notas académicas.","https://www.lascondes.cl/educacion/"],
["lascondes","Las Condes",RM,"310.000 hab.","https://lascondes.cl","Adulto Mayor","👴","Tarjeta Vecino Mayor Las Condes","Tarjeta con descuentos y beneficios exclusivos para adultos mayores residentes en Las Condes.","Solicita tu tarjeta en la Municipalidad con carnet de identidad y acreditando residencia en Las Condes.","https://www.lascondes.cl/adulto-mayor/"],
["lascondes","Las Condes",RM,"310.000 hab.","https://lascondes.cl","Social y Legal","⚖️","Tarjeta Vecino — más de 1.000 convenios","Tarjeta digital gratuita con descuentos en gastronomía, salud, bencina y más para residentes de Las Condes.","Obtén tu Tarjeta Vecino en la Municipalidad con carnet de identidad y acreditando residencia.","https://www.lascondes.cl/tarjeta-vecino/"],

# Lo Barnechea
["lobarnechea","Lo Barnechea",RM,"115.000 hab.","https://lobarnechea.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://lobarnechea.cl/salud/"],
["lobarnechea","Lo Barnechea",RM,"115.000 hab.","https://lobarnechea.cl","Salud","🏥","Farmacia Municipal Lo Barnechea","Medicamentos a precio social para vecinos de Lo Barnechea con receta médica vigente.","Presenta receta médica en la farmacia municipal con carnet de identidad.","https://lobarnechea.cl/"],
["lobarnechea","Lo Barnechea",RM,"115.000 hab.","https://lobarnechea.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Lo Barnechea con vulnerabilidad cursando educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad.","https://lobarnechea.cl/educacion/"],
["lobarnechea","Lo Barnechea",RM,"115.000 hab.","https://lobarnechea.cl","Adulto Mayor","👴","Programa Adulto Mayor Lo Barnechea","Talleres de actividad física y recreación gratuitos para personas mayores de 60 años.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Lo Barnechea.","https://lobarnechea.cl/adulto-mayor/"],
["lobarnechea","Lo Barnechea",RM,"115.000 hab.","https://lobarnechea.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Urgencias sociales, subsidios y orientación para familias vulnerables de Lo Barnechea.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://lobarnechea.cl/social/"],

# Lo Espejo
["loespejo","Lo Espejo",RM,"115.000 hab.","https://loespejo.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Red de centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://loespejo.cl/salud/"],
["loespejo","Lo Espejo",RM,"115.000 hab.","https://loespejo.cl","Salud","🏥","Farmacia Municipal Lo Espejo","Medicamentos esenciales a precio accesible para vecinos con receta médica vigente.","Presenta receta médica en la farmacia municipal con carnet de identidad.","https://loespejo.cl/"],
["loespejo","Lo Espejo",RM,"115.000 hab.","https://loespejo.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Lo Espejo con vulnerabilidad cursando educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad.","https://loespejo.cl/educacion/"],
["loespejo","Lo Espejo",RM,"115.000 hab.","https://loespejo.cl","Adulto Mayor","👴","Programa Adulto Mayor Lo Espejo","Talleres recreativos y de actividad física gratuitos para personas mayores de 60 años.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Lo Espejo.","https://loespejo.cl/adulto-mayor/"],
["loespejo","Lo Espejo",RM,"115.000 hab.","https://loespejo.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Urgencias sociales, subsidios y orientación para familias vulnerables de Lo Espejo.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://loespejo.cl/social/"],

# Lo Prado
["loprado","Lo Prado",RM,"120.000 hab.","https://loprado.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa inscritos.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://loprado.cl/salud/"],
["loprado","Lo Prado",RM,"120.000 hab.","https://loprado.cl","Salud","🏥","Farmacia Municipal Lo Prado","Medicamentos a precio social para vecinos de Lo Prado con receta médica vigente.","Presenta receta médica en la farmacia municipal con carnet de identidad.","https://loprado.cl/"],
["loprado","Lo Prado",RM,"120.000 hab.","https://loprado.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Lo Prado con vulnerabilidad cursando educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad.","https://loprado.cl/educacion/"],
["loprado","Lo Prado",RM,"120.000 hab.","https://loprado.cl","Adulto Mayor","👴","Programa Adulto Mayor Lo Prado","Talleres gratuitos de actividad física, recreación y sociabilización para mayores de 60 años.","Inscríbete en la Oficina del Adulto Mayor o en tu centro comunitario de Lo Prado.","https://loprado.cl/adulto-mayor/"],
["loprado","Lo Prado",RM,"120.000 hab.","https://loprado.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Atención de urgencias sociales, subsidios y orientación para familias vulnerables de Lo Prado.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://loprado.cl/social/"],

# Macul
["macul","Macul",RM,"125.000 hab.","https://macul.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Red de centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://macul.cl/salud/"],
["macul","Macul",RM,"125.000 hab.","https://macul.cl","Salud","🏥","Farmacia Municipal Macul","Medicamentos a precio accesible para vecinos de Macul con receta médica vigente.","Presenta receta médica en la farmacia municipal con carnet de identidad.","https://macul.cl/"],
["macul","Macul",RM,"125.000 hab.","https://macul.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Macul con vulnerabilidad cursando educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad de Macul.","https://macul.cl/educacion/"],
["macul","Macul",RM,"125.000 hab.","https://macul.cl","Adulto Mayor","👴","Programa Adulto Mayor Macul","Talleres recreativos y de actividad física gratuitos para personas mayores de 60 años de Macul.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Macul.","https://macul.cl/adulto-mayor/"],
["macul","Macul",RM,"125.000 hab.","https://macul.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Urgencias sociales, subsidios y orientación para familias vulnerables de Macul.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://macul.cl/social/"],

# Ñuñoa
["nunoa","Ñuñoa",RM,"175.000 hab.","https://nunoa.cl","Salud","🏥","CESFAM y vacunación municipal","Centros de salud familiar con médico, dental, matrona y salud mental. Centro de vacunación con agenda online.","Inscríbete en el CESFAM de tu sector o agenda vacunas en nunoa.cl.","https://nunoa.cl/salud/"],
["nunoa","Ñuñoa",RM,"175.000 hab.","https://nunoa.cl","Social y Legal","⚖️","Tarjeta Vecino Ñuñoa","Tarjeta de descuentos en comercios, servicios y gastronomía para vecinos residentes en Ñuñoa.","Obtén tu Tarjeta Vecino en la Municipalidad con carnet de identidad y certificado de residencia.","https://nunoa.cl/tarjeta-vecino/"],
["nunoa","Ñuñoa",RM,"175.000 hab.","https://nunoa.cl","Educación y Becas","🎓","Fondos Concursables y Becas Municipales","Fondos para proyectos comunitarios y becas para estudiantes de Ñuñoa con vulnerabilidad.","Postula en la Municipalidad o en nunoa.cl entre marzo y abril de cada año.","https://nunoa.cl/educacion/"],
["nunoa","Ñuñoa",RM,"175.000 hab.","https://nunoa.cl","Adulto Mayor","👴","Programa Adulto Mayor Ñuñoa","Talleres culturales, de actividad física y recreación gratuitos para personas mayores de 60 años.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Ñuñoa.","https://nunoa.cl/adulto-mayor/"],
["nunoa","Ñuñoa",RM,"175.000 hab.","https://nunoa.cl","Social y Legal","⚖️","Defensoría de la Familia y Víctimas","Atención y orientación jurídica gratuita para familias y víctimas de delitos en Ñuñoa.","Acércate a la Defensoría de la Familia en la Municipalidad de Ñuñoa. Atención confidencial.","https://nunoa.cl/social/"],

# Pedro Aguirre Cerda
["pac","Pedro Aguirre Cerda",RM,"125.000 hab.","https://mpac.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://www.mpac.cl/salud/"],
["pac","Pedro Aguirre Cerda",RM,"125.000 hab.","https://mpac.cl","Salud","🏥","Farmacia Municipal Pedro Aguirre Cerda","Medicamentos a precio accesible para vecinos de Pedro Aguirre Cerda con receta médica vigente.","Presenta receta médica en la farmacia municipal con carnet de identidad.","https://www.mpac.cl/"],
["pac","Pedro Aguirre Cerda",RM,"125.000 hab.","https://mpac.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de la comuna con vulnerabilidad cursando educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad.","https://www.mpac.cl/educacion/"],
["pac","Pedro Aguirre Cerda",RM,"125.000 hab.","https://mpac.cl","Adulto Mayor","👴","Programa Adulto Mayor PAC","Talleres gratuitos de actividad física y recreación para personas mayores de 60 años de PAC.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Pedro Aguirre Cerda.","https://www.mpac.cl/adulto-mayor/"],
["pac","Pedro Aguirre Cerda",RM,"125.000 hab.","https://mpac.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Urgencias sociales, subsidios y orientación para familias vulnerables de Pedro Aguirre Cerda.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://www.mpac.cl/social/"],

# Providencia
["providencia","Providencia",RM,"145.000 hab.","https://providencia.cl","Salud","🏥","Farmacia Provisalud","Farmacia municipal con dos locales (Salvador y Los Leones) con medicamentos a precio rebajado para vecinos.","Acércate a cualquiera de las dos sucursales con receta médica y carnet. Sin inscripción previa.","https://www.providencia.cl/salud/"],
["providencia","Providencia",RM,"145.000 hab.","https://providencia.cl","Salud","🏥","Vacúnate en tu Plaza","Campaña de vacunación gratuita en plazas y espacios públicos de Providencia para toda la comunidad.","Revisa el calendario de vacunación en providencia.cl o en las redes sociales del municipio.","https://www.providencia.cl/salud/"],
["providencia","Providencia",RM,"145.000 hab.","https://providencia.cl","Educación y Becas","🎓","Beca Municipal y apoyo educacional","Apoyo económico para estudiantes de Providencia con vulnerabilidad cursando educación superior o media.","Postula entre marzo y abril en la Municipalidad con RSH, matrícula y notas académicas.","https://www.providencia.cl/educacion/"],
["providencia","Providencia",RM,"145.000 hab.","https://providencia.cl","Adulto Mayor","👴","Programa Estamos Seguros","Charlas de seguridad, talleres y actividades gratuitas para adultos mayores de Providencia.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Providencia.","https://www.providencia.cl/adulto-mayor/"],
["providencia","Providencia",RM,"145.000 hab.","https://providencia.cl","Social y Legal","⚖️","Tarjeta Vecino Providencia","Tarjeta con descuentos en comercios, servicios y restaurantes para residentes en Providencia.","Obtén tu tarjeta en la Municipalidad con carnet de identidad y acreditando residencia.","https://www.providencia.cl/tarjeta-vecino/"],
["providencia","Providencia",RM,"145.000 hab.","https://providencia.cl","Social y Legal","⚖️","FONDEVE — Mejoramiento del Hogar","Fondo para mejoras habitacionales dirigido a vecinos de Providencia en situación de vulnerabilidad.","Postula en la Municipalidad. Requiere RSH y acreditar residencia en Providencia.","https://www.providencia.cl/social/"],

# Quinta Normal
["quintanormal","Quinta Normal",RM,"120.000 hab.","https://quintanormal.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Red de centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://quintanormal.cl/salud/"],
["quintanormal","Quinta Normal",RM,"120.000 hab.","https://quintanormal.cl","Salud","🏥","Farmacia Municipal Quinta Normal","Medicamentos a precio accesible para vecinos de Quinta Normal con receta médica vigente.","Presenta receta médica en la farmacia municipal con carnet de identidad.","https://quintanormal.cl/"],
["quintanormal","Quinta Normal",RM,"120.000 hab.","https://quintanormal.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Quinta Normal con vulnerabilidad en educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad.","https://quintanormal.cl/educacion/"],
["quintanormal","Quinta Normal",RM,"120.000 hab.","https://quintanormal.cl","Adulto Mayor","👴","Programa Adulto Mayor Quinta Normal","Talleres recreativos y de actividad física gratuitos para personas mayores de 60 años.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Quinta Normal.","https://quintanormal.cl/adulto-mayor/"],
["quintanormal","Quinta Normal",RM,"120.000 hab.","https://quintanormal.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Urgencias sociales, subsidios y orientación para familias vulnerables de Quinta Normal.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://quintanormal.cl/social/"],

# Renca
["renca","Renca",RM,"155.000 hab.","https://renca.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa inscritos.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://renca.cl/salud/"],
["renca","Renca",RM,"155.000 hab.","https://renca.cl","Salud","🏥","Farmacia Municipal Renca","Medicamentos a precio accesible para vecinos de Renca con receta médica vigente.","Presenta receta médica en la farmacia municipal con carnet de identidad.","https://renca.cl/"],
["renca","Renca",RM,"155.000 hab.","https://renca.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Renca con vulnerabilidad cursando educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad de Renca.","https://renca.cl/educacion/"],
["renca","Renca",RM,"155.000 hab.","https://renca.cl","Adulto Mayor","👴","Programa Adulto Mayor Renca","Talleres gratuitos de recreación y actividad física para personas mayores de 60 años de Renca.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Renca.","https://renca.cl/adulto-mayor/"],
["renca","Renca",RM,"155.000 hab.","https://renca.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Urgencias sociales, subsidios y orientación para familias vulnerables de Renca.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://renca.cl/social/"],

# San Joaquín
["sanjoaquin","San Joaquín",RM,"100.000 hab.","https://msanjoaquin.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://www.msanjoaquin.cl/salud/"],
["sanjoaquin","San Joaquín",RM,"100.000 hab.","https://msanjoaquin.cl","Salud","🏥","Farmacia Municipal San Joaquín","Medicamentos a precio social para vecinos de San Joaquín con receta médica vigente.","Presenta receta médica en la farmacia municipal con carnet de identidad.","https://www.msanjoaquin.cl/"],
["sanjoaquin","San Joaquín",RM,"100.000 hab.","https://msanjoaquin.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de San Joaquín con vulnerabilidad cursando educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad.","https://www.msanjoaquin.cl/educacion/"],
["sanjoaquin","San Joaquín",RM,"100.000 hab.","https://msanjoaquin.cl","Adulto Mayor","👴","Programa Adulto Mayor San Joaquín","Talleres recreativos y de actividad física gratuitos para personas mayores de 60 años.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de San Joaquín.","https://www.msanjoaquin.cl/adulto-mayor/"],
["sanjoaquin","San Joaquín",RM,"100.000 hab.","https://msanjoaquin.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Urgencias sociales, subsidios y orientación para familias vulnerables de San Joaquín.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://www.msanjoaquin.cl/social/"],

# San Miguel
["sanmiguel","San Miguel",RM,"120.000 hab.","https://msanmiguel.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Red de centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://www.msanmiguel.cl/salud/"],
["sanmiguel","San Miguel",RM,"120.000 hab.","https://msanmiguel.cl","Salud","🏥","Farmacia Municipal San Miguel","Medicamentos a precio accesible para vecinos de San Miguel con receta médica vigente.","Presenta receta médica en la farmacia municipal con carnet de identidad.","https://www.msanmiguel.cl/"],
["sanmiguel","San Miguel",RM,"120.000 hab.","https://msanmiguel.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de San Miguel con vulnerabilidad cursando educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad de San Miguel.","https://www.msanmiguel.cl/educacion/"],
["sanmiguel","San Miguel",RM,"120.000 hab.","https://msanmiguel.cl","Adulto Mayor","👴","Programa Adulto Mayor San Miguel","Talleres gratuitos de actividad física y recreación para personas mayores de 60 años.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de San Miguel.","https://www.msanmiguel.cl/adulto-mayor/"],
["sanmiguel","San Miguel",RM,"120.000 hab.","https://msanmiguel.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Urgencias sociales, subsidios y orientación para familias vulnerables de San Miguel.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://www.msanmiguel.cl/social/"],

# San Ramón
["sanramon","San Ramón",RM,"100.000 hab.","https://msanramon.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa inscritos.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://www.msanramon.cl/salud/"],
["sanramon","San Ramón",RM,"100.000 hab.","https://msanramon.cl","Salud","🏥","Farmacia Municipal San Ramón","Medicamentos a precio social para vecinos de San Ramón con receta médica vigente.","Presenta receta médica en la farmacia municipal con carnet de identidad.","https://www.msanramon.cl/"],
["sanramon","San Ramón",RM,"100.000 hab.","https://msanramon.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de San Ramón con vulnerabilidad cursando educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad de San Ramón.","https://www.msanramon.cl/educacion/"],
["sanramon","San Ramón",RM,"100.000 hab.","https://msanramon.cl","Adulto Mayor","👴","Programa Adulto Mayor San Ramón","Talleres recreativos y de actividad física gratuitos para personas mayores de 60 años.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de San Ramón.","https://www.msanramon.cl/adulto-mayor/"],
["sanramon","San Ramón",RM,"100.000 hab.","https://msanramon.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Urgencias sociales, subsidios y orientación para familias vulnerables de San Ramón.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://www.msanramon.cl/social/"],

# Vitacura
["vitacura","Vitacura",RM,"90.000 hab.","https://vitacura.cl","Salud","🏥","Vitabotica — Farmacia Municipal","Farmacia municipal con consulta de precios online. Medicamentos a precio justo para vecinos de Vitacura.","Consulta precios en vitacura.cl y acércate con receta médica y carnet. Requiere residencia en Vitacura.","https://www.vitacura.cl/vitabotica/"],
["vitacura","Vitacura",RM,"90.000 hab.","https://vitacura.cl","Salud","🏥","Ambulancia gratuita 24/7","Servicio de ambulancia municipal gratuito las 24 horas para emergencias médicas de vecinos de Vitacura.","Llama al número de emergencias de la Municipalidad de Vitacura. Disponible las 24 horas.","https://www.vitacura.cl/salud/"],
["vitacura","Vitacura",RM,"90.000 hab.","https://vitacura.cl","Adulto Mayor","👴","Vitamayor — Programa Adulto Mayor","Actividades recreativas, culturales y entretenimiento especializado para adultos mayores de Vitacura.","Inscríbete en el programa Vitamayor a través de vitacura.cl o en la Municipalidad.","https://www.vitacura.cl/adulto-mayor/"],
["vitacura","Vitacura",RM,"90.000 hab.","https://vitacura.cl","Adulto Mayor","👴","Tarjeta de alimentos y aseo personal","Apoyo en alimentos y productos de aseo para adultos mayores vulnerables de Vitacura.","Postula en la Municipalidad con RSH y carnet de identidad. Evaluación de asistente social.","https://www.vitacura.cl/adulto-mayor/"],
["vitacura","Vitacura",RM,"90.000 hab.","https://vitacura.cl","Social y Legal","⚖️","Tarjeta Mi Vita — Descuentos vecinos","Tarjeta de descuentos en comercios y servicios para residentes de Vitacura.","Obtén tu tarjeta en la Municipalidad con carnet de identidad y acreditando residencia en Vitacura.","https://www.vitacura.cl/tarjeta-mi-vita/"],

# ─── PROVINCIA DE CHACABUCO ────────────────────────────────────────────
# Colina
["colina","Colina",RM,"150.000 hab.","https://municipalidadcolina.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://municipalidadcolina.cl/salud/"],
["colina","Colina",RM,"150.000 hab.","https://municipalidadcolina.cl","Salud","🏥","Farmacia Municipal Colina","Medicamentos a precio accesible para vecinos de Colina con receta médica vigente.","Presenta receta médica en la farmacia municipal con carnet de identidad.","https://municipalidadcolina.cl/"],
["colina","Colina",RM,"150.000 hab.","https://municipalidadcolina.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Colina con vulnerabilidad cursando educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad de Colina.","https://municipalidadcolina.cl/educacion/"],
["colina","Colina",RM,"150.000 hab.","https://municipalidadcolina.cl","Adulto Mayor","👴","Programa Adulto Mayor Colina","Talleres gratuitos de actividad física y recreación para personas mayores de 60 años de Colina.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Colina.","https://municipalidadcolina.cl/adulto-mayor/"],
["colina","Colina",RM,"150.000 hab.","https://municipalidadcolina.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Urgencias sociales, subsidios y orientación para familias vulnerables de Colina.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://municipalidadcolina.cl/social/"],

# Lampa
["lampa","Lampa",RM,"100.000 hab.","https://municipalidadlampa.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://municipalidadlampa.cl/salud/"],
["lampa","Lampa",RM,"100.000 hab.","https://municipalidadlampa.cl","Salud","🏥","Farmacia Municipal Lampa","Medicamentos a precio social para vecinos de Lampa con receta médica vigente.","Presenta receta médica en la farmacia municipal con carnet de identidad.","https://municipalidadlampa.cl/"],
["lampa","Lampa",RM,"100.000 hab.","https://municipalidadlampa.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Lampa con vulnerabilidad cursando educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad de Lampa.","https://municipalidadlampa.cl/educacion/"],
["lampa","Lampa",RM,"100.000 hab.","https://municipalidadlampa.cl","Adulto Mayor","👴","Programa Adulto Mayor Lampa","Talleres recreativos y de actividad física gratuitos para personas mayores de 60 años de Lampa.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Lampa.","https://municipalidadlampa.cl/adulto-mayor/"],
["lampa","Lampa",RM,"100.000 hab.","https://municipalidadlampa.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Urgencias sociales, subsidios y orientación para familias de Lampa.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://municipalidadlampa.cl/social/"],

# Tiltil
["tiltil","Tiltil",RM,"20.000 hab.","https://municipalidadtiltil.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Atención de salud familiar gratuita con médico, dental y matrona para vecinos de Tiltil con Fonasa inscritos.","Inscríbete en el CESFAM de Tiltil con carnet de identidad.","https://municipalidadtiltil.cl/salud/"],
["tiltil","Tiltil",RM,"20.000 hab.","https://municipalidadtiltil.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Tiltil con vulnerabilidad cursando educación superior.","Postula en la Municipalidad con RSH, matrícula y notas académicas entre marzo y abril.","https://municipalidadtiltil.cl/educacion/"],
["tiltil","Tiltil",RM,"20.000 hab.","https://municipalidadtiltil.cl","Adulto Mayor","👴","Programa Adulto Mayor Tiltil","Talleres y actividades recreativas gratuitas para personas mayores de 60 años de Tiltil.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Tiltil.","https://municipalidadtiltil.cl/adulto-mayor/"],
["tiltil","Tiltil",RM,"20.000 hab.","https://municipalidadtiltil.cl","Social y Legal","⚖️","Desarrollo Social Municipal","Urgencias sociales, subsidios y orientación para familias de Tiltil.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://municipalidadtiltil.cl/social/"],

# ─── PROVINCIA DE CORDILLERA ───────────────────────────────────────────
# Pirque
["pirque","Pirque",RM,"25.000 hab.","https://mpirque.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Atención de salud familiar gratuita con médico, dental y matrona para vecinos de Pirque con Fonasa.","Inscríbete en el CESFAM de Pirque con carnet de identidad.","https://mpirque.cl/salud/"],
["pirque","Pirque",RM,"25.000 hab.","https://mpirque.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Pirque con vulnerabilidad cursando educación superior.","Postula en la Municipalidad con RSH, matrícula y notas entre marzo y abril.","https://mpirque.cl/educacion/"],
["pirque","Pirque",RM,"25.000 hab.","https://mpirque.cl","Adulto Mayor","👴","Programa Adulto Mayor Pirque","Actividades recreativas y de bienestar gratuitas para adultos mayores de 60 años de Pirque.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Pirque.","https://mpirque.cl/adulto-mayor/"],
["pirque","Pirque",RM,"25.000 hab.","https://mpirque.cl","Social y Legal","⚖️","Desarrollo Social Municipal","Urgencias sociales, subsidios y orientación para familias de Pirque.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://mpirque.cl/social/"],

# San José de Maipo
["sanjosedemaipo","San José de Maipo",RM,"30.000 hab.","https://municipalidadsanjosedemaipo.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Atención de salud familiar gratuita con médico, dental y matrona para vecinos con Fonasa inscritos.","Inscríbete en el CESFAM de San José de Maipo con carnet de identidad.","https://municipalidadsanjosedemaipo.cl/salud/"],
["sanjosedemaipo","San José de Maipo",RM,"30.000 hab.","https://municipalidadsanjosedemaipo.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de la comuna con vulnerabilidad cursando educación superior.","Postula en la Municipalidad con RSH, matrícula y notas entre marzo y abril.","https://municipalidadsanjosedemaipo.cl/educacion/"],
["sanjosedemaipo","San José de Maipo",RM,"30.000 hab.","https://municipalidadsanjosedemaipo.cl","Adulto Mayor","👴","Programa Adulto Mayor","Actividades recreativas y de bienestar gratuitas para adultos mayores de 60 años.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de San José de Maipo.","https://municipalidadsanjosedemaipo.cl/adulto-mayor/"],
["sanjosedemaipo","San José de Maipo",RM,"30.000 hab.","https://municipalidadsanjosedemaipo.cl","Social y Legal","⚖️","Desarrollo Social Municipal","Urgencias sociales, subsidios y orientación para familias de San José de Maipo.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://municipalidadsanjosedemaipo.cl/social/"],

# ─── PROVINCIA DE MAIPO ────────────────────────────────────────────────
# Buin
["buin","Buin",RM,"85.000 hab.","https://municipalidadbuin.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://municipalidadbuin.cl/salud/"],
["buin","Buin",RM,"85.000 hab.","https://municipalidadbuin.cl","Salud","🏥","Farmacia Municipal Buin","Medicamentos a precio social para vecinos de Buin con receta médica vigente.","Presenta receta médica en la farmacia municipal con carnet de identidad.","https://municipalidadbuin.cl/"],
["buin","Buin",RM,"85.000 hab.","https://municipalidadbuin.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Buin con vulnerabilidad cursando educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad de Buin.","https://municipalidadbuin.cl/educacion/"],
["buin","Buin",RM,"85.000 hab.","https://municipalidadbuin.cl","Adulto Mayor","👴","Programa Adulto Mayor Buin","Talleres gratuitos de actividad física y recreación para personas mayores de 60 años de Buin.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Buin.","https://municipalidadbuin.cl/adulto-mayor/"],
["buin","Buin",RM,"85.000 hab.","https://municipalidadbuin.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Urgencias sociales, subsidios y orientación para familias vulnerables de Buin.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://municipalidadbuin.cl/social/"],

# Calera de Tango
["caleradetango","Calera de Tango",RM,"25.000 hab.","https://municipalidadcaleradetango.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Atención de salud familiar gratuita con médico, dental y matrona para vecinos con Fonasa inscritos.","Inscríbete en el CESFAM de Calera de Tango con carnet de identidad.","https://municipalidadcaleradetango.cl/salud/"],
["caleradetango","Calera de Tango",RM,"25.000 hab.","https://municipalidadcaleradetango.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de la comuna con vulnerabilidad en educación superior.","Postula en la Municipalidad con RSH, matrícula y notas entre marzo y abril.","https://municipalidadcaleradetango.cl/educacion/"],
["caleradetango","Calera de Tango",RM,"25.000 hab.","https://municipalidadcaleradetango.cl","Adulto Mayor","👴","Programa Adulto Mayor","Actividades recreativas gratuitas para adultos mayores de 60 años de Calera de Tango.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Calera de Tango.","https://municipalidadcaleradetango.cl/adulto-mayor/"],
["caleradetango","Calera de Tango",RM,"25.000 hab.","https://municipalidadcaleradetango.cl","Social y Legal","⚖️","Desarrollo Social Municipal","Urgencias sociales, subsidios y orientación para familias de Calera de Tango.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://municipalidadcaleradetango.cl/social/"],

# Isla de Maipo
["islademaipo","Isla de Maipo",RM,"35.000 hab.","https://muniidem.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Atención de salud familiar gratuita con médico, dental y matrona para vecinos de Isla de Maipo con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://muniidem.cl/salud/"],
["islademaipo","Isla de Maipo",RM,"35.000 hab.","https://muniidem.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Isla de Maipo con vulnerabilidad en educación superior.","Postula en la Municipalidad con RSH, matrícula y notas entre marzo y abril.","https://muniidem.cl/educacion/"],
["islademaipo","Isla de Maipo",RM,"35.000 hab.","https://muniidem.cl","Adulto Mayor","👴","Programa Adulto Mayor Isla de Maipo","Actividades recreativas y de bienestar gratuitas para adultos mayores de 60 años.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Isla de Maipo.","https://muniidem.cl/adulto-mayor/"],
["islademaipo","Isla de Maipo",RM,"35.000 hab.","https://muniidem.cl","Social y Legal","⚖️","Desarrollo Social Municipal","Urgencias sociales, subsidios y orientación para familias de Isla de Maipo.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://muniidem.cl/social/"],

# Paine
["paine","Paine",RM,"80.000 hab.","https://municipalidadpaine.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://municipalidadpaine.cl/salud/"],
["paine","Paine",RM,"80.000 hab.","https://municipalidadpaine.cl","Salud","🏥","Farmacia Municipal Paine","Medicamentos a precio accesible para vecinos de Paine con receta médica vigente.","Presenta receta médica en la farmacia municipal con carnet de identidad.","https://municipalidadpaine.cl/"],
["paine","Paine",RM,"80.000 hab.","https://municipalidadpaine.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Paine con vulnerabilidad cursando educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad de Paine.","https://municipalidadpaine.cl/educacion/"],
["paine","Paine",RM,"80.000 hab.","https://municipalidadpaine.cl","Adulto Mayor","👴","Programa Adulto Mayor Paine","Talleres recreativos y de actividad física gratuitos para personas mayores de 60 años de Paine.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Paine.","https://municipalidadpaine.cl/adulto-mayor/"],
["paine","Paine",RM,"80.000 hab.","https://municipalidadpaine.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Urgencias sociales, subsidios y orientación para familias vulnerables de Paine.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://municipalidadpaine.cl/social/"],

# ─── PROVINCIA DE MELIPILLA ────────────────────────────────────────────
# Alhué
["alhue","Alhué",RM,"5.000 hab.","https://municipalidadalhue.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Atención de salud familiar gratuita con médico, dental y matrona para vecinos de Alhué con Fonasa inscritos.","Inscríbete en el CESFAM de Alhué con carnet de identidad.","https://municipalidadalhue.cl/salud/"],
["alhue","Alhué",RM,"5.000 hab.","https://municipalidadalhue.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Alhué con vulnerabilidad cursando educación superior.","Postula en la Municipalidad con RSH, matrícula y notas entre marzo y abril.","https://municipalidadalhue.cl/educacion/"],
["alhue","Alhué",RM,"5.000 hab.","https://municipalidadalhue.cl","Adulto Mayor","👴","Programa Adulto Mayor Alhué","Actividades recreativas y de bienestar gratuitas para adultos mayores de 60 años de Alhué.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Alhué.","https://municipalidadalhue.cl/adulto-mayor/"],
["alhue","Alhué",RM,"5.000 hab.","https://municipalidadalhue.cl","Social y Legal","⚖️","Desarrollo Social Municipal","Urgencias sociales, subsidios y orientación para familias de Alhué.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://municipalidadalhue.cl/social/"],

# Curacaví
["curacavi","Curacaví",RM,"30.000 hab.","https://municipalidadcuracavi.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://municipalidadcuracavi.cl/salud/"],
["curacavi","Curacaví",RM,"30.000 hab.","https://municipalidadcuracavi.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Curacaví con vulnerabilidad cursando educación superior.","Postula en la Municipalidad con RSH, matrícula y notas entre marzo y abril.","https://municipalidadcuracavi.cl/educacion/"],
["curacavi","Curacaví",RM,"30.000 hab.","https://municipalidadcuracavi.cl","Adulto Mayor","👴","Programa Adulto Mayor Curacaví","Actividades recreativas gratuitas para adultos mayores de 60 años de Curacaví.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Curacaví.","https://municipalidadcuracavi.cl/adulto-mayor/"],
["curacavi","Curacaví",RM,"30.000 hab.","https://municipalidadcuracavi.cl","Social y Legal","⚖️","Desarrollo Social Municipal","Urgencias sociales, subsidios y orientación para familias de Curacaví.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://municipalidadcuracavi.cl/social/"],

# María Pinto
["mariapinto","María Pinto",RM,"20.000 hab.","https://municipalidadmariapinto.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Atención de salud familiar gratuita con médico, dental y matrona para vecinos de María Pinto con Fonasa.","Inscríbete en el CESFAM de María Pinto con carnet de identidad.","https://municipalidadmariapinto.cl/salud/"],
["mariapinto","María Pinto",RM,"20.000 hab.","https://municipalidadmariapinto.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de María Pinto con vulnerabilidad cursando educación superior.","Postula en la Municipalidad con RSH, matrícula y notas entre marzo y abril.","https://municipalidadmariapinto.cl/educacion/"],
["mariapinto","María Pinto",RM,"20.000 hab.","https://municipalidadmariapinto.cl","Adulto Mayor","👴","Programa Adulto Mayor María Pinto","Actividades recreativas y de bienestar gratuitas para adultos mayores de 60 años.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de María Pinto.","https://municipalidadmariapinto.cl/adulto-mayor/"],
["mariapinto","María Pinto",RM,"20.000 hab.","https://municipalidadmariapinto.cl","Social y Legal","⚖️","Desarrollo Social Municipal","Urgencias sociales, subsidios y orientación para familias de María Pinto.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://municipalidadmariapinto.cl/social/"],

# Melipilla
["melipilla","Melipilla",RM,"130.000 hab.","https://melipilla.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Red de centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://melipilla.cl/salud/"],
["melipilla","Melipilla",RM,"130.000 hab.","https://melipilla.cl","Salud","🏥","Farmacia Municipal Melipilla","Medicamentos a precio social para vecinos de Melipilla con receta médica vigente.","Presenta receta médica en la farmacia municipal con carnet de identidad.","https://melipilla.cl/"],
["melipilla","Melipilla",RM,"130.000 hab.","https://melipilla.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Melipilla con vulnerabilidad cursando educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad de Melipilla.","https://melipilla.cl/educacion/"],
["melipilla","Melipilla",RM,"130.000 hab.","https://melipilla.cl","Adulto Mayor","👴","Programa Adulto Mayor Melipilla","Talleres recreativos y de actividad física gratuitos para personas mayores de 60 años.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Melipilla.","https://melipilla.cl/adulto-mayor/"],
["melipilla","Melipilla",RM,"130.000 hab.","https://melipilla.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Urgencias sociales, subsidios y orientación para familias vulnerables de Melipilla.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://melipilla.cl/social/"],

# San Pedro
["sanpedro","San Pedro",RM,"15.000 hab.","https://municipalidadsanpedro.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Atención de salud familiar gratuita con médico, dental y matrona para vecinos de San Pedro con Fonasa.","Inscríbete en el CESFAM de San Pedro con carnet de identidad.","https://municipalidadsanpedro.cl/salud/"],
["sanpedro","San Pedro",RM,"15.000 hab.","https://municipalidadsanpedro.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de San Pedro con vulnerabilidad cursando educación superior.","Postula en la Municipalidad con RSH, matrícula y notas entre marzo y abril.","https://municipalidadsanpedro.cl/educacion/"],
["sanpedro","San Pedro",RM,"15.000 hab.","https://municipalidadsanpedro.cl","Adulto Mayor","👴","Programa Adulto Mayor San Pedro","Actividades recreativas y de bienestar gratuitas para adultos mayores de 60 años de San Pedro.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de San Pedro.","https://municipalidadsanpedro.cl/adulto-mayor/"],
["sanpedro","San Pedro",RM,"15.000 hab.","https://municipalidadsanpedro.cl","Social y Legal","⚖️","Desarrollo Social Municipal","Urgencias sociales, subsidios y orientación para familias de San Pedro.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://municipalidadsanpedro.cl/social/"],

# ─── PROVINCIA DE TALAGANTE ────────────────────────────────────────────
# El Monte
["elmonte","El Monte",RM,"35.000 hab.","https://municipalidadelmonte.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de El Monte con carnet de identidad.","https://municipalidadelmonte.cl/salud/"],
["elmonte","El Monte",RM,"35.000 hab.","https://municipalidadelmonte.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de El Monte con vulnerabilidad cursando educación superior.","Postula en la Municipalidad con RSH, matrícula y notas entre marzo y abril.","https://municipalidadelmonte.cl/educacion/"],
["elmonte","El Monte",RM,"35.000 hab.","https://municipalidadelmonte.cl","Adulto Mayor","👴","Programa Adulto Mayor El Monte","Actividades recreativas y de bienestar gratuitas para adultos mayores de 60 años de El Monte.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de El Monte.","https://municipalidadelmonte.cl/adulto-mayor/"],
["elmonte","El Monte",RM,"35.000 hab.","https://municipalidadelmonte.cl","Social y Legal","⚖️","Desarrollo Social Municipal","Urgencias sociales, subsidios y orientación para familias de El Monte.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://municipalidadelmonte.cl/social/"],

# Padre Hurtado
["padrehurtado","Padre Hurtado",RM,"70.000 hab.","https://municipalidadpadrehurtado.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://municipalidadpadrehurtado.cl/salud/"],
["padrehurtado","Padre Hurtado",RM,"70.000 hab.","https://municipalidadpadrehurtado.cl","Salud","🏥","Farmacia Municipal Padre Hurtado","Medicamentos a precio social para vecinos de Padre Hurtado con receta médica vigente.","Presenta receta médica en la farmacia municipal con carnet de identidad.","https://municipalidadpadrehurtado.cl/"],
["padrehurtado","Padre Hurtado",RM,"70.000 hab.","https://municipalidadpadrehurtado.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Padre Hurtado con vulnerabilidad en educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad.","https://municipalidadpadrehurtado.cl/educacion/"],
["padrehurtado","Padre Hurtado",RM,"70.000 hab.","https://municipalidadpadrehurtado.cl","Adulto Mayor","👴","Programa Adulto Mayor Padre Hurtado","Talleres gratuitos de actividad física y recreación para personas mayores de 60 años.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Padre Hurtado.","https://municipalidadpadrehurtado.cl/adulto-mayor/"],
["padrehurtado","Padre Hurtado",RM,"70.000 hab.","https://municipalidadpadrehurtado.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Urgencias sociales, subsidios y orientación para familias de Padre Hurtado.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://municipalidadpadrehurtado.cl/social/"],

# Peñaflor
["penaflor","Peñaflor",RM,"100.000 hab.","https://municipalidadpenaflor.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://municipalidadpenaflor.cl/salud/"],
["penaflor","Peñaflor",RM,"100.000 hab.","https://municipalidadpenaflor.cl","Salud","🏥","Farmacia Municipal Peñaflor","Medicamentos a precio accesible para vecinos de Peñaflor con receta médica vigente.","Presenta receta médica en la farmacia municipal con carnet de identidad.","https://municipalidadpenaflor.cl/"],
["penaflor","Peñaflor",RM,"100.000 hab.","https://municipalidadpenaflor.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Peñaflor con vulnerabilidad cursando educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad de Peñaflor.","https://municipalidadpenaflor.cl/educacion/"],
["penaflor","Peñaflor",RM,"100.000 hab.","https://municipalidadpenaflor.cl","Adulto Mayor","👴","Programa Adulto Mayor Peñaflor","Talleres recreativos y de actividad física gratuitos para personas mayores de 60 años.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Peñaflor.","https://municipalidadpenaflor.cl/adulto-mayor/"],
["penaflor","Peñaflor",RM,"100.000 hab.","https://municipalidadpenaflor.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Urgencias sociales, subsidios y orientación para familias vulnerables de Peñaflor.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://municipalidadpenaflor.cl/social/"],

# Talagante
["talagante","Talagante",RM,"80.000 hab.","https://municipalidadtalagante.cl","Salud","🏥","CESFAM y Atención Primaria gratuita","Centros de salud familiar con médico, dental, matrona y salud mental gratuita para vecinos con Fonasa.","Inscríbete en el CESFAM de tu sector con carnet de identidad.","https://municipalidadtalagante.cl/salud/"],
["talagante","Talagante",RM,"80.000 hab.","https://municipalidadtalagante.cl","Salud","🏥","Farmacia Municipal Talagante","Medicamentos a precio social para vecinos de Talagante con receta médica vigente.","Presenta receta médica en la farmacia municipal con carnet de identidad.","https://municipalidadtalagante.cl/"],
["talagante","Talagante",RM,"80.000 hab.","https://municipalidadtalagante.cl","Educación y Becas","🎓","Beca Municipal Educación Superior","Apoyo económico para estudiantes de Talagante con vulnerabilidad cursando educación superior.","Postula entre marzo y abril con RSH, matrícula y notas en la Municipalidad de Talagante.","https://municipalidadtalagante.cl/educacion/"],
["talagante","Talagante",RM,"80.000 hab.","https://municipalidadtalagante.cl","Adulto Mayor","👴","Programa Adulto Mayor Talagante","Talleres recreativos y de actividad física gratuitos para personas mayores de 60 años.","Inscríbete en la Oficina del Adulto Mayor de la Municipalidad de Talagante.","https://municipalidadtalagante.cl/adulto-mayor/"],
["talagante","Talagante",RM,"80.000 hab.","https://municipalidadtalagante.cl","Social y Legal","⚖️","Dirección de Desarrollo Social","Urgencias sociales, subsidios y orientación para familias vulnerables de Talagante.","Acércate con carnet e RSH a la Dirección de Desarrollo Social de la Municipalidad.","https://municipalidadtalagante.cl/social/"],
]

# Leer CSV existente
csv_path = os.path.join(os.path.dirname(__file__), "..", "datos-sheets", "municipios.csv")
with open(csv_path, "r", encoding="utf-8") as f:
    existentes = list(csv.reader(f))

# Agregar nuevas filas
with open(csv_path, "a", encoding="utf-8", newline="") as f:
    writer = csv.writer(f)
    for row in nuevos:
        writer.writerow(row)

ids_nuevos = set(r[0] for r in nuevos)
print(f"Municipios nuevos agregados: {len(ids_nuevos)}")
print(f"Filas nuevas: {len(nuevos)}")
print(f"Total filas en CSV: {len(existentes) + len(nuevos)}")
print("Listo!")
